run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: github.com/stevengreensill/fast-cc-git-hooks

  govet:
    enable-all: true

  misspell:
    locale: US

  gofmt:
    simplify: true

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint

  revive:
    rules:
      - name: exported
        arguments: [checkPrivateReceivers]
      - name: unreachable-code
      - name: unused-parameter
      - name: unused-receiver

linters:
  enable:
    - bodyclose
    - errcheck
    - gocyclo
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - gocritic
    - gosec
    - prealloc
    - unconvert
    - unparam
    - whitespace
    - gocognit
    - godot
    - gofumpt
    - goheader
    - goprintffuncname
    - gosimple
    - makezero
    - nilerr
    - nilnil
    - nolintlint
    - predeclared
    - tparallel
    - wastedassign

  disable:
    - gochecknoinits
    - gochecknoglobals
    - lll
    - funlen
    - godox
    - exhaustive

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - unparam

    # Exclude known linters from generated files
    - path: ".*\\.pb\\.go"
      linters:
        - maligned
        - lll

    # Exclude shadow checking on type switches
    - text: "shadow: declaration of"
      linters:
        - govet

  exclude:
    # errcheck: Almost all programs ignore errors on these functions
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked

  max-issues-per-linter: 0
  max-same-issues: 0