version: 1

project_name: fcgh

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: fcgh
    main: ./cmd/fcgh
    binary: fcgh
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
    flags:
      - -trimpath

  - id: cc
    main: ./cmd/cc
    binary: cc
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
    flags:
      - -trimpath

  - id: ccc
    main: ./cmd/ccc
    binary: ccc
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - src: example-configs/
        dst: example-configs
        strip_parent: true

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: greenstevester
    name: fast-cc-git-hooks
  draft: false
  prerelease: auto
  mode: replace
  header: |
    # 🚀 fcgh {{.Tag}}

    **The easiest way to write better commit messages!**

    ## 🆕 What's New in This Release
    
    This release includes **two powerful tools**:
    - **`fcgh`** - Fast Conventional Git Hooks for enforcing conventional commits
    - **`cc`** - Helper utility for generating commit messages automatically

    ## ⚡️ Super Quick Setup (2 steps!)

    ### Step 1: Download for your platform

    **🐧 Linux:**
    ```bash
    # Most common (AMD64)
    curl -L -o fcgh.tar.gz https://github.com/greenstevester/fast-cc-git-hooks/releases/download/{{.Tag}}/fcgh_{{.Tag}}_linux_amd64.tar.gz
    tar -xzf fcgh.tar.gz
    chmod +x fcgh cc
    sudo mv fcgh cc /usr/local/bin/

    # ARM64 (Raspberry Pi, etc.)
    curl -L -o fcgh.tar.gz https://github.com/greenstevester/fast-cc-git-hooks/releases/download/{{.Tag}}/fcgh_{{.Tag}}_linux_arm64.tar.gz
    tar -xzf fcgh.tar.gz
    chmod +x fcgh cc
    sudo mv fcgh cc /usr/local/bin/
    ```

    **🍎 macOS:**
    ```bash
    # Intel Macs
    curl -L -o fcgh.tar.gz https://github.com/greenstevester/fast-cc-git-hooks/releases/download/{{.Tag}}/fcgh_{{.Tag}}_darwin_amd64.tar.gz
    tar -xzf fcgh.tar.gz
    chmod +x fcgh cc
    sudo mv fcgh cc /usr/local/bin/

    # Apple Silicon (M1/M2/M3)
    curl -L -o fcgh.tar.gz https://github.com/greenstevester/fast-cc-git-hooks/releases/download/{{.Tag}}/fcgh_{{.Tag}}_darwin_arm64.tar.gz
    tar -xzf fcgh.tar.gz
    chmod +x fcgh cc
    sudo mv fcgh cc /usr/local/bin/
    ```

    **🪟 Windows:**
    ```powershell
    # Download and extract fcgh_{{.Tag}}_windows_amd64.zip
    # Add both fcgh.exe and cc.exe to your PATH
    ```

    ### Step 2: Set it up (takes 5 seconds!)
    ```bash
    fcgh setup
    ```

    **That's it!** 🎉 Now every time you make a commit, it will automatically check that your message is good!

    ## 🤖 NEW: Automatic Commit Message Generation
    
    Use the included `cc` helper to automatically generate conventional commit messages:
    ```bash
    cc                    # Preview generated commit message
    ccc                   # Generate and commit automatically
    cc --verbose          # Show detailed analysis
    ```

  footer: |
    ## 🐳 Docker (Advanced Users)
    ```bash
    docker pull ghcr.io/greenstevester/fcgh:{{.Tag}}
    ```

    ## 📦 Package Managers
    - **Ubuntu/Debian:** Download `.deb` file and run `sudo dpkg -i fcgh_{{.Tag}}_linux_amd64.deb`
    - **RHEL/CentOS:** Download `.rpm` file and run `sudo rpm -i fcgh_{{.Tag}}_linux_amd64.rpm`
    
    ## 🍺 Coming Soon
    - **Homebrew:** `brew install greenstevester/tap/fcgh`
    - **Windows Scoop:** `scoop install fcgh`

    ---
    💡 **Need help?** Run `fcgh -h` for super friendly help!

# Homebrew formula - disabled until repository is created
# brews:
#   - repository:
#       owner: greenstevester
#       name: homebrew-tap
#     folder: Formula
#     homepage: https://github.com/greenstevester/fast-cc-git-hooks
#     description: "Fast conventional commits git hooks"
#     license: MIT
#     test: |
#       system "#{bin}/fast-cc-hooks --version"

# Docker images - disabled until Docker setup is fixed
# dockers:
#   - image_templates:
#       - "ghcr.io/greenstevester/fast-cc-hooks:{{ .Tag }}"
#       - "ghcr.io/greenstevester/fast-cc-hooks:v{{ .Major }}"
#       - "ghcr.io/greenstevester/fast-cc-hooks:v{{ .Major }}.{{ .Minor }}"
#       - "ghcr.io/greenstevester/fast-cc-hooks:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - --platform=linux/amd64
#       - --label=org.opencontainers.image.title={{ .ProjectName }}
#       - --label=org.opencontainers.image.description=Fast conventional commits git hooks
#       - --label=org.opencontainers.image.url=https://github.com/greenstevester/fast-cc-git-hooks
#       - --label=org.opencontainers.image.source=https://github.com/greenstevester/fast-cc-git-hooks
#       - --label=org.opencontainers.image.version={{ .Version }}
#       - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#       - --label=org.opencontainers.image.revision={{ .FullCommit }}
#       - --label=org.opencontainers.image.licenses=MIT

# Snapcraft packages - disabled for now
# snapcrafts:
#   - name: fast-cc-hooks
#     summary: Fast conventional commits git hooks
#     description: |
#       A high-performance pre-commit git hook system for enforcing conventional commits.
#       Supports custom validation rules, flexible configuration, and fast execution.
#     grade: stable
#     confinement: strict
#     publish: true
#     license: MIT

# Windows Scoop bucket - disabled until repository is created
# scoops:
#   - repository:
#       owner: greenstevester
#       name: scoop-bucket
#     homepage: https://github.com/greenstevester/fast-cc-git-hooks
#     description: "Fast conventional commits git hooks"
#     license: MIT

# Linux packages via nFPM
nfpms:
  - id: packages
    package_name: fcgh
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Steven Greensill
    homepage: https://github.com/greenstevester/fast-cc-git-hooks
    maintainer: greenstevester
    description: Fast conventional commits git hooks
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin