version: 1

project_name: fast-cc-hooks

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: fast-cc-hooks
    main: ./cmd/fast-cc-hooks
    binary: fast-cc-hooks
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
    flags:
      - -trimpath

  - id: gc
    main: ./cmd/gc
    binary: gc
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
    flags:
      - -trimpath

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - fast-cc-hooks
      - gc
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - examples/

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Performance Improvements"
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: "Other Changes"
      order: 999

release:
  github:
    owner: stevengreensill
    name: fast-cc-git-hooks
  draft: false
  prerelease: auto
  mode: replace
  header: |
    # 🚀 fast-cc-hooks {{.Tag}}

    **The easiest way to write better commit messages!**

    ## 🆕 What's New in This Release
    
    This release includes **two powerful tools**:
    - **`fast-cc-hooks`** - Git hook for enforcing conventional commits
    - **`gc`** - Helper utility for generating commit messages automatically

    ## ⚡️ Super Quick Setup (2 steps!)

    ### Step 1: Download for your platform

    **🐧 Linux:**
    ```bash
    # Most common (AMD64)
    curl -L -o fast-cc-hooks.tar.gz https://github.com/stevengreensill/fast-cc-git-hooks/releases/download/{{.Tag}}/fast-cc-hooks_{{.Tag}}_linux_amd64.tar.gz
    tar -xzf fast-cc-hooks.tar.gz
    chmod +x fast-cc-hooks gc
    sudo mv fast-cc-hooks gc /usr/local/bin/

    # ARM64 (Raspberry Pi, etc.)
    curl -L -o fast-cc-hooks.tar.gz https://github.com/stevengreensill/fast-cc-git-hooks/releases/download/{{.Tag}}/fast-cc-hooks_{{.Tag}}_linux_arm64.tar.gz
    tar -xzf fast-cc-hooks.tar.gz
    chmod +x fast-cc-hooks gc
    sudo mv fast-cc-hooks gc /usr/local/bin/
    ```

    **🍎 macOS:**
    ```bash
    # Intel Macs
    curl -L -o fast-cc-hooks.tar.gz https://github.com/stevengreensill/fast-cc-git-hooks/releases/download/{{.Tag}}/fast-cc-hooks_{{.Tag}}_darwin_amd64.tar.gz
    tar -xzf fast-cc-hooks.tar.gz
    chmod +x fast-cc-hooks gc
    sudo mv fast-cc-hooks gc /usr/local/bin/

    # Apple Silicon (M1/M2/M3)
    curl -L -o fast-cc-hooks.tar.gz https://github.com/stevengreensill/fast-cc-git-hooks/releases/download/{{.Tag}}/fast-cc-hooks_{{.Tag}}_darwin_arm64.tar.gz
    tar -xzf fast-cc-hooks.tar.gz
    chmod +x fast-cc-hooks gc
    sudo mv fast-cc-hooks gc /usr/local/bin/
    ```

    **🪟 Windows:**
    ```powershell
    # Download and extract fast-cc-hooks_{{.Tag}}_windows_amd64.zip
    # Add both fast-cc-hooks.exe and gc.exe to your PATH
    ```

    ### Step 2: Set it up (takes 5 seconds!)
    ```bash
    fast-cc-hooks setup
    ```

    **That's it!** 🎉 Now every time you make a commit, it will automatically check that your message is good!

    ## 🤖 NEW: Automatic Commit Message Generation
    
    Use the included `gc` helper to automatically generate conventional commit messages:
    ```bash
    gc                    # Preview generated commit message
    gc --execute          # Generate and commit automatically
    gc --verbose          # Show detailed analysis
    ```

  footer: |
    ## 🐳 Docker (Advanced Users)
    ```bash
    docker pull ghcr.io/stevengreensill/fast-cc-hooks:{{.Tag}}
    ```

    ## 📦 Package Managers
    - **Ubuntu/Debian:** Download `.deb` file and run `sudo dpkg -i fast-cc-hooks_{{.Tag}}_linux_amd64.deb`
    - **RHEL/CentOS:** Download `.rpm` file and run `sudo rpm -i fast-cc-hooks_{{.Tag}}_linux_amd64.rpm`
    
    ## 🍺 Coming Soon
    - **Homebrew:** `brew install greenstevester/tap/fast-cc-hooks`
    - **Windows Scoop:** `scoop install fast-cc-hooks`

    ---
    💡 **Need help?** Run `fast-cc-hooks -h` for super friendly help!

# Homebrew formula - disabled until repository is created
# brews:
#   - repository:
#       owner: greenstevester
#       name: homebrew-tap
#     folder: Formula
#     homepage: https://github.com/stevengreensill/fast-cc-git-hooks
#     description: "Fast conventional commits git hooks"
#     license: MIT
#     test: |
#       system "#{bin}/fast-cc-hooks --version"

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/stevengreensill/fast-cc-hooks:{{ .Tag }}"
      - "ghcr.io/stevengreensill/fast-cc-hooks:v{{ .Major }}"
      - "ghcr.io/stevengreensill/fast-cc-hooks:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/stevengreensill/fast-cc-hooks:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Fast conventional commits git hooks
      - --label=org.opencontainers.image.url=https://github.com/stevengreensill/fast-cc-git-hooks
      - --label=org.opencontainers.image.source=https://github.com/stevengreensill/fast-cc-git-hooks
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT

# Snapcraft packages
snapcrafts:
  - name: fast-cc-hooks
    summary: Fast conventional commits git hooks
    description: |
      A high-performance pre-commit git hook system for enforcing conventional commits.
      Supports custom validation rules, flexible configuration, and fast execution.
    grade: stable
    confinement: strict
    publish: true
    license: MIT

# Windows Scoop bucket - disabled until repository is created
# scoops:
#   - repository:
#       owner: greenstevester
#       name: scoop-bucket
#     homepage: https://github.com/stevengreensill/fast-cc-git-hooks
#     description: "Fast conventional commits git hooks"
#     license: MIT

# Linux packages via nFPM
nfpms:
  - id: packages
    package_name: fast-cc-hooks
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Steven Greensill
    homepage: https://github.com/stevengreensill/fast-cc-git-hooks
    maintainer: Steven Greensill <stevengreensill@example.com>
    description: Fast conventional commits git hooks
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin