name: Test Release Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

env:
  GO_VERSION: '1.25'

jobs:
  test-release:
    name: Test Release Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Run tests
      run: make test

    - name: Test GoReleaser build
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: build --snapshot --clean --skip-validate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify binaries were built
      run: |
        echo "Checking built binaries:"
        find dist/ -name "fcgh*" -type f -exec ls -la {} \;
        
        # Test that binaries work
        echo "Testing Linux binary:"
        ./dist/fcgh_linux_amd64_v1/fcgh --version
        
        echo "Testing macOS binary:"
        # Note: We can't actually run macOS binary on Linux, but we can check it exists
        ls -la ./dist/fcgh_darwin_amd64_v1/fcgh

    - name: Test friendly help output
      run: |
        echo "Testing friendly help output:"
        ./dist/fcgh_linux_amd64_v1/fcgh -h