name: Test Release Build

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

env:
  GO_VERSION: '1.21'

jobs:
  test-release:
    name: Test Release Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true

    - name: Run tests
      run: make test

    - name: Test GoReleaser build
      uses: goreleaser/goreleaser-action@v5
      with:
        distribution: goreleaser
        version: latest
        args: build --snapshot --clean --skip-validate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify binaries were built
      run: |
        echo "Checking built binaries:"
        find dist/ -name "fast-cc-hooks*" -type f -exec ls -la {} \;
        
        # Test that binaries work
        echo "Testing Linux binary:"
        ./dist/fast-cc-hooks_linux_amd64_v1/fast-cc-hooks --version
        
        echo "Testing macOS binary:"
        # Note: We can't actually run macOS binary on Linux, but we can check it exists
        ls -la ./dist/fast-cc-hooks_darwin_amd64_v1/fast-cc-hooks

    - name: Test friendly help output
      run: |
        echo "Testing friendly help output:"
        ./dist/fast-cc-hooks_linux_amd64_v1/fast-cc-hooks -h